---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: platform
data:
  redis-url: redis-master.platform.svc.cluster.local
  channel: "orders"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adaptor-operator
  namespace: platform
  labels:
    app: adaptor-operator
    type: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adaptor-operator
  template:
    metadata:
      labels:
        app: adaptor-operator
        name: platform
    spec:
      containers:
      - name: main
        image: registry.labs:5000/labs/adaptor-operator
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: CHANNEL
          valueFrom:
            configMapKeyRef:
              name: config
              key: channel
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: redis-url
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: adaptor-operator
  namespace: platform
spec:
  type: ClusterIP
  selector:
    app: adaptor-operator
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adaptor-operator
  namespace: platform
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /adaptor-operator(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: adaptor-operator
            port:
              number: 80