---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui 
  namespace: ui
  labels:
    app: ui
    type: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: registry.labs:5000/labs/ui
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: ui
spec:
  type: ClusterIP
  selector:
    app: ui
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui
  namespace: ui
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /ui(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ui
            port:
              number: 80
