apiVersion: k3d.io/v1alpha3
kind: Simple 
name: k3d-lab
servers: 1 
agents: 1
image: rancher/k3s:v1.21.5-k3s2
  # rancher/k3s:v1.21.1-rc1-k3s1
  # image: rancher/k3s:v1.21.3-k3s1
  # rancher/k3s:v1.21.5-k3s2
registries:
  create:
    name: registry.labs
    host: "0.0.0.0"
    hostPort: "5000"
volumes:
  - volume: /tmp/volumes/k3d/:/volumes/k3d
    nodeFilters:
      - agent:*
ports:
  - port: 30000:30000
    nodeFilters:
      - agent:0
  - port: 30001:30001
    nodeFilters:
      - agent:0
  - port: 30002:30002
    nodeFilters:
      - agent:0
options:
  k3d: 
    wait: true 
    timeout: "60s" 
    disableImageVolume: false 
  kubeconfig:
    updateDefaultKubeconfig: true 
    switchCurrentContext: true 
  k3s:
    nodeLabels:
      - label: sharedvol=true
        nodeFilters:
          - agent:*
