apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: adaptor-sidecarset
spec:
  selector:
    matchLabels:
      sidecar: adaptor
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
  volumes:
    - name: registry
      configMap:
        name: config
        items:
          - key: event-endpoint-event
            path: "event-endpoint-event"
  containers:
    - name: adaptor
      image: registry.labs:5000/labs/event-adaptor:1.0.5
      transferEnv:
        - sourceContainerName: main
          envName: REDIS_URL
        - sourceContainerName: main
          envName: REDIS_PASSWORD
        - sourceContainerName: main
          envName: SERVICE
      shareVolumePolicy:
        type: enabled
      volumeMounts:
        - name: registry
          mountPath: "/registry"
          readOnly: true
