---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-event-mappings
  namespace: platform
data:
  redis-url: redis-master.platform.svc.cluster.local
  event-service-event: |
    order.submitted.1|contexts-orders.order.validate|order.validated.1
    order.validated.1|contexts-orders.order.create|order.created.1
    order.created.1|contexts-orders.order.authorise|order.authorised.1
    order.authorised.1|contexts-orders.order.fulfil|order.ship.1
    order.ship.1|contexts-orders.order.ship|order.shipped.1
    order.received.1|contexts-orders.order.received|order.close.1
    order.cancelled.1|contexts-orders.order.cancel|order.cancelled.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adaptor
  namespace: platform
  labels:
    app: adaptor
    type: service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adaptor
  template:
    metadata:
      labels:
        app: adaptor
    spec:
      volumes:
        - name: registry
          configMap:
            name: service-event-mappings
            items:
              - key: "event-service-event"
                path: "event-service-event"
      containers:
        - name: adaptor
          image: bryandollery/redis-rest-adaptor
          ports:
            - containerPort: 80
          volumeMounts:
            - name: registry
              mountPath: "/registry"
              readOnly: true
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: password
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: service-event-mappings
                  key: redis-url
---
apiVersion: v1
kind: Service
metadata:
  name: adaptor
  namespace: platform
spec:
  type: ClusterIP
  selector:
    app: adaptor
  ports:
    - port: 80
      targetPort: 80
