---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifsui 
  namespace: ui
  labels:
    app: ifsui
    type: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ifsui
  template:
    metadata:
      labels:
        app: ifsui
    spec:
      containers:
      - name: ifsui
        image: bryandollery/ifsui
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ifsui
  namespace: ui
spec:
  type: ClusterIP
  selector:
    app: ifsui
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ifsui
  namespace: ui
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /ifsui(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ifsui
            port:
              number: 80
